import { Select, SelectItem } from "@nextui-org/react";
import React, { memo } from "react";

const countries = [
  { key: "", label: "All countries" },
  { key: "af", label: "Afghanistan" },
  { key: "ax", label: "Åland Islands" },
  { key: "al", label: "Albania" },
  { key: "dz", label: "Algeria" },
  { key: "as", label: "American Samoa" },
  { key: "ad", label: "Andorra" },
  { key: "ao", label: "Angola" },
  { key: "ai", label: "Anguilla" },
  { key: "aq", label: "Antarctica" },
  { key: "ag", label: "Antigua and Barbuda" },
  { key: "ar", label: "Argentina" },
  { key: "am", label: "Armenia" },
  { key: "aw", label: "Aruba" },
  { key: "au", label: "Australia" },
  { key: "at", label: "Austria" },
  { key: "az", label: "Azerbaijan" },
  { key: "bs", label: "Bahamas" },
  { key: "bh", label: "Bahrain" },
  { key: "bd", label: "Bangladesh" },
  { key: "bb", label: "Barbados" },
  { key: "by", label: "Belarus" },
  { key: "be", label: "Belgium" },
  { key: "bz", label: "Belize" },
  { key: "bj", label: "Benin" },
  { key: "bm", label: "Bermuda" },
  { key: "bt", label: "Bhutan" },
  { key: "bo", label: "Bolivia" },
  { key: "bq", label: "Bonaire" },
  { key: "ba", label: "Bosnia and Herzegovina" },
  { key: "bw", label: "Botswana" },
  { key: "bv", label: "Bouvet Island" },
  { key: "br", label: "Brazil" },
  { key: "io", label: "Indian Ocean Territory (British)" },
  { key: "vg", label: "Virgin (British)" },
  { key: "vi", label: "Virgin (U.S.)" },
  { key: "bn", label: "Brunei Darussalam" },
  { key: "bg", label: "Bulgaria" },
  { key: "bf", label: "Burkina Faso" },
  { key: "bi", label: "Burundi" },
  { key: "kh", label: "Cambodia" },
  { key: "cm", label: "Cameroon" },
  { key: "ca", label: "Canada" },
  { key: "cv", label: "Cabo Verde" },
  { key: "ky", label: "Cayman Islands" },
  { key: "cf", label: "Central African Republic" },
  { key: "td", label: "Chad" },
  { key: "cl", label: "Chile" },
  { key: "cn", label: "China" },
  { key: "cx", label: "Christmas Island" },
  { key: "cc", label: "Cocos" },
  { key: "co", label: "Colombia" },
  { key: "km", label: "Comoros" },
  { key: "cg", label: "Congo" },
  { key: "cd", label: "Congo, DR" },
  { key: "ck", label: "Cook Islands" },
  { key: "cr", label: "Costa Rica" },
  { key: "hr", label: "Croatia" },
  { key: "cu", label: "Cuba" },
  { key: "cw", label: "Curaçao" },
  { key: "cy", label: "Cyprus" },
  { key: "cz", label: "Czech Republic" },
  { key: "dk", label: "Denmark" },
  { key: "dj", label: "Djibouti" },
  { key: "dm", label: "Dominica" },
  { key: "do", label: "Dominican Republic" },
  { key: "ec", label: "Ecuador" },
  { key: "eg", label: "Egypt" },
  { key: "sv", label: "El Salvador" },
  { key: "gq", label: "Equatorial Guinea" },
  { key: "er", label: "Eritrea" },
  { key: "ee", label: "Estonia" },
  { key: "et", label: "Ethiopia" },
  { key: "fk", label: "Falkland Islands" },
  { key: "fo", label: "Faroe Islands" },
  { key: "fj", label: "Fiji" },
  { key: "fi", label: "Finland" },
  { key: "fr", label: "France" },
  { key: "gf", label: "French Guiana" },
  { key: "pf", label: "French Polynesia" },
  { key: "ga", label: "Gabon" },
  { key: "gm", label: "Gambia" },
  { key: "ge", label: "Georgia" },
  { key: "de", label: "Germany" },
  { key: "gh", label: "Ghana" },
  { key: "gi", label: "Gibraltar" },
  { key: "gr", label: "Greece" },
  { key: "gl", label: "Greenland" },
  { key: "gd", label: "Grenada" },
  { key: "gp", label: "Guadeloupe" },
  { key: "gu", label: "Guam" },
  { key: "gt", label: "Guatemala" },
  { key: "gg", label: "Guernsey" },
  { key: "gn", label: "Guinea" },
  { key: "gw", label: "Guinea-Bissau" },
  { key: "gy", label: "Guyana" },
  { key: "ht", label: "Haiti" },
  { key: "hm", label: "Heard Island" },
  { key: "va", label: "Holy See" },
  { key: "hn", label: "Honduras" },
  { key: "hk", label: "Hong Kong" },
  { key: "hu", label: "Hungary" },
  { key: "is", label: "Iceland" },
  { key: "in", label: "India" },
  { key: "id", label: "Indonesia" },
  { key: "ci", label: "Côte d'Ivoire" },
  { key: "ir", label: "Iran" },
  { key: "iq", label: "Iraq" },
  { key: "ie", label: "Ireland" },
  { key: "im", label: "Isle of Man" },
  { key: "il", label: "Israel" },
  { key: "it", label: "Italy" },
  { key: "jm", label: "Jamaica" },
  { key: "jp", label: "Japan" },
  { key: "je", label: "Jersey" },
  { key: "jo", label: "Jordan" },
  { key: "kz", label: "Kazakhstan" },
  { key: "ke", label: "Kenya" },
  { key: "ki", label: "Kiribati" },
  { key: "kw", label: "Kuwait" },
  { key: "kg", label: "Kyrgyzstan" },
  { key: "la", label: "Lao Peoples DR" },
  { key: "lv", label: "Latvia" },
  { key: "lb", label: "Lebanon" },
  { key: "ls", label: "Lesotho" },
  { key: "lr", label: "Liberia" },
  { key: "ly", label: "Libya" },
  { key: "li", label: "Liechtenstein" },
  { key: "lt", label: "Lithuania" },
  { key: "lu", label: "Luxembourg" },
  { key: "mo", label: "Macao" },
  { key: "mk", label: "Macedonia)" },
  { key: "mg", label: "Madagascar" },
  { key: "mw", label: "Malawi" },
  { key: "my", label: "Malaysia" },
  { key: "mv", label: "Maldives" },
  { key: "ml", label: "Mali" },
  { key: "mt", label: "Malta" },
  { key: "mh", label: "Marshall Islands" },
  { key: "mq", label: "Martinique" },
  { key: "mr", label: "Mauritania" },
  { key: "mu", label: "Mauritius" },
  { key: "yt", label: "Mayotte" },
  { key: "mx", label: "Mexico" },
  { key: "fm", label: "Micronesia" },
  { key: "md", label: "Moldova, Republic of" },
  { key: "mc", label: "Monaco" },
  { key: "mn", label: "Mongolia" },
  { key: "me", label: "Montenegro" },
  { key: "ms", label: "Montserrat" },
  { key: "ma", label: "Morocco" },
  { key: "mz", label: "Mozambique" },
  { key: "mm", label: "Myanmar" },
  { key: "na", label: "Namibia" },
  { key: "nr", label: "Nauru" },
  { key: "np", label: "Nepal" },
  { key: "nl", label: "Netherlands" },
  { key: "nc", label: "New Caledonia" },
  { key: "nz", label: "New Zealand" },
  { key: "ni", label: "Nicaragua" },
  { key: "ne", label: "Niger" },
  { key: "ng", label: "Nigeria" },
  { key: "nu", label: "Niue" },
  { key: "nf", label: "Norfolk Island" },
  { key: "kp", label: "Korea DR" },
  { key: "mp", label: "Northern Mariana" },
  { key: "no", label: "Norway" },
  { key: "om", label: "Oman" },
  { key: "pk", label: "Pakistan" },
  { key: "pw", label: "Palau" },
  { key: "ps", label: "Palestinian" },
  { key: "pa", label: "Panama" },
  { key: "pg", label: "Papua New Guinea" },
  { key: "py", label: "Paraguay" },
  { key: "pe", label: "Peru" },
  { key: "ph", label: "Philippines" },
  { key: "pn", label: "Pitcairn" },
  { key: "pl", label: "Poland" },
  { key: "pt", label: "Portugal" },
  { key: "pr", label: "Puerto Rico" },
  { key: "qa", label: "Qatar" },
  { key: "xk", label: "Republic of Kosovo" },
  { key: "re", label: "Réunion" },
  { key: "ro", label: "Romania" },
  { key: "ru", label: "Russian Federation" },
  { key: "rw", label: "Rwanda" },
  { key: "bl", label: "Saint Barthélemy" },
  { key: "sh", label: "Saint Helena" },
  { key: "kn", label: "Saint Kitts and Nevis" },
  { key: "lc", label: "Saint Lucia" },
  { key: "mf", label: "Saint Martin" },
  { key: "pm", label: "Saint Pierre" },
  { key: "vc", label: "Saint Vincent" },
  { key: "ws", label: "Samoa" },
  { key: "sm", label: "San Marino" },
  { key: "st", label: "Sao Tome and Principe" },
  { key: "sa", label: "Saudi Arabia" },
  { key: "sn", label: "Senegal" },
  { key: "rs", label: "Serbia" },
  { key: "sc", label: "Seychelles" },
  { key: "sl", label: "Sierra Leone" },
  { key: "sg", label: "Singapore" },
  { key: "sx", label: "Sint Maarten" },
  { key: "sk", label: "Slovakia" },
  { key: "si", label: "Slovenia" },
  { key: "sb", label: "Solomon Islands" },
  { key: "so", label: "Somalia" },
  { key: "za", label: "South Africa" },
  { key: "gs", label: "South Georgia" },
  { key: "kr", label: "Korea, Republic of" },
  { key: "ss", label: "South Sudan" },
  { key: "es", label: "Spain" },
  { key: "lk", label: "Sri Lanka" },
  { key: "sd", label: "Sudan" },
  { key: "sr", label: "Suriname" },
  { key: "sj", label: "Svalbard and Jan Mayen" },
  { key: "sz", label: "Swaziland" },
  { key: "se", label: "Sweden" },
  { key: "ch", label: "Switzerland" },
  { key: "sy", label: "Syrian Arab Republic" },
  { key: "tw", label: "Taiwan" },
  { key: "tj", label: "Tajikistan" },
  { key: "tz", label: "Tanzania, UR" },
  { key: "th", label: "Thailand" },
  { key: "tl", label: "Timor-Leste" },
  { key: "tg", label: "Togo" },
  { key: "tk", label: "Tokelau" },
  { key: "to", label: "Tonga" },
  { key: "tt", label: "Trinidad and Tobago" },
  { key: "tn", label: "Tunisia" },
  { key: "tr", label: "Turkey" },
  { key: "tm", label: "Turkmenistan" },
  { key: "tc", label: "Turks and Caicos Islands" },
  { key: "tv", label: "Tuvalu" },
  { key: "ug", label: "Uganda" },
  { key: "ua", label: "Ukraine" },
]

interface CountrySelectProps {
  value: string;
  onChange: (value: string) => void;
}

export const CountrySelect: React.FC<CountrySelectProps> = memo(({ value, onChange }) => {
  const countryOptions = React.useMemo(() => (
    countries.map((country) => (
      <SelectItem key={country.key} value={country.key}>
        {country.label}
      </SelectItem>
    ))
  ), []);

  return (
    <Select
      aria-labelledby="countryLabel"
      aria-label="countryLabel"
      disallowEmptySelection
      value={value} 
      onChange={(e) => onChange(e.target.value)} 
      placeholder="Select"
      className="max-w-xs shadow-xl rounded-xl"
      defaultSelectedKeys={[""]}
    >
      {countryOptions}
    </Select> 
  );
});